// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2023-10-17 14:42:54.829273 +0100 BST m=+0.002587334
// using data from
// resourceDefinition.json and resourceDefinition_out_of_docs.json

package azurecaf

// ResourceDefinitions are a map of difinitions for the resources supported
var ResourceDefinitions = map[string]ResourceStructure{
	"azurerm_resource_group": {"azurerm_resource_group", "rg", 1, 90, false, `[^a-zA-Z0-9-._\\(\\)]`, "^[a-zA-Z0-9-._\\(\\)]{0,89}[a-zA-Z0-9-_\\(\\)]$", true, "subscription"},
	"gke_kubernetes_cluster": {"gke_kubernetes_cluster", "gke", 1, 63, false, "[^0-9A-Za-z_-]", "^[a-zA-Z0-9][a-zA-Z0-9-_]{0,61}[a-zA-Z0-9]$", true, "resourceGroup"},
}

// ResourceMaps are a map from the slug to the resource definition
var ResourceMaps = map[string]string{
	"gke": "gke_kubernetes_cluster",
	"rg":  "azurerm_resource_group",
}
